# Dependencias
FROM node:21-alpine3.19 as deps

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --force 

# Builder
FROM node:21-alpine3.19 as build

WORKDIR /usr/src/app

#Copiar de deps, los modulos de node
COPY --from=deps /usr/src/app/node_modules ./node_modules

#copiar todo el codigo fuente de la aplicacion
COPY . . 

RUN npm run build

#Limpieza de cache
RUN npm ci -f --only=production && npm cache clean --force

# Crear imagen final
FROM node:21-alpine3.19 as prod

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app/dist ./dist

ENV NODE_ENV=production


# USER node

# RUN chown -R node.node /usr/app/node_modules

CMD ["node", "dist/main.js"]

#docker build -f dockerfile.prod -t poc_backend .